version: '3'

# split services
# restarts: always - in case it fails
# ports mapping - 3000 in local machine, 8080 in container
# ports mapping - 27018 in local machine, 27017 in container
# image - not building from a docker file, we`re pulling the image from docker hub 
# links - link app service to mongo service

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'
