version: '3'

# split services
# restarts: always - in case it fails
# ports mapping - 80 in local machine, 3000 in container
# ports mapping - 27017 both in local machine and container
# image - not building from a docker file, we`re pulling the image from docker hub 
# links - link app service to mongo service

services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
